### ISSUE TITLE
log1pexp(x) when x < -37

### ISSUE THREAD

**Issue by cossio** [JuliaStats/LogExpFunctions.jl#13]
I was reading R's implementation of `log1pexp` and they include one additional branch (see https://cran.r-project.org/web/packages/Rmpfr/vignettes/log1mexp-note.pdf, equation 10). 

Currently StatsFuns does this:

https://github.com/JuliaStats/StatsFuns.jl/blob/ae40bc1c6ee63a5624ba6cd168da5bf43f473e59/src/basicfuns.jl#L66

Whereas including the additional branch it would be:

```julia
log1pexp_v2(x::AbstractFloat) = x ≤ -37. ? exp(x) : x ≤ 18. ? log1p(exp(x)) : x ≤ 33.3 ? x + exp(-x) : x
```

Apparently including the `x < -37.` check reduces the function's computation time by 25% (because it saves the call to `log1p` I guess). But I am no expert doing this kind of performance tests so please can someone else more knowledgeable check this? Here is the test I did:

```julia
using BenchmarkTools
@btime for x = -100. : 1. : 100., _ = 1 : 100
    log1pexp_v2(x)
end   #  310.471 μs (0 allocations: 0 bytes)
@btime for x = -100. : 1. : 100., _ = 1 : 100
    log1pexp(x)
end  #   423.671 μs (0 allocations: 0 bytes)
```

Both `log1pexp_v2` and `log1pexp` give numerically identical results.

If this is worth it I can prepare a PR. 

**Update:** Actually it seems much of the time is due to the `oftype(exp(-x), x)` bit in the final branch. I think specializing on `AbstractFloat` would take care of that. Even after this change the `x ≤ -37.` check is faster.

**Comment by Uroc327** [comment]
If I may ask, what's the current state of this?

**Comment by devmotion** [comment]
I don't know, I just transferred the issue when `log1pexp` was moved from StatsFuns to LogExpFunctions. @cossio, do you plan to open a PR to LogExpFunctions that preferably also addresses the comments in https://github.com/JuliaStats/StatsFuns.jl/pull/70?

**Comment by tpapp** [comment]
JuliaStats/StatsFuns.jl#70 was just closed, but a PR here is welcome.

**Comment by cossio** [comment]
I'll do a PR right after https://github.com/JuliaStats/LogExpFunctions.jl/pull/35 is done.

**Comment by tpapp** [comment]
Great, thanks!
