### ISSUE TITLE
logcosh

### ISSUE THREAD

**Issue by cossio** [JuliaStats/LogExpFunctions.jl#31]
Currently `logcosh(x) = log(cosh(x))` is defined in NNlib like this:

```
logcosh(x) = x + softplus(-2x) - oftype(float(x), log(2))
```

It probably makes sense to have this function here, since it is a "log-exp-function" ...

**Comment by devmotion** [comment]
Yes, probably makes sense to add it. We should use a numerically more stable implementation and handle `log(2)` better, eg. with something like
```julia
function logcosh(x::Real)
    abs_x = abs(x)
    return abs_x + log1pexp(-2 * abs_x) - logtwo
end
```
I'll put together a PR.

**Comment by cossio** [comment]
Great thanks.

But why do you say that `abs(x) + log1pexp(-2 * abs(x))` is better than `x + softplus(-2x)`?

Do you have an example where one fails (is less accurate) and the other doesn't?

**Comment by devmotion** [comment]
I'm away from my computer so I haven't tried a concrete example. It is just the natural thing to do and resembles the situation you face eg in `logaddexp`, so I assume it would be best to use the same approach here. More concretely, mathematically we have
```math
log(cosh(x)) = log(exp(-x) + exp(x)) - log(2)
```
which corresponds to
```julia
logcosh(x) = logaddexp(-x, x) - log(2)
```
I just expanded the implementation of `logaddexp` which pulls out the maximum of both values, ie. `abs(x)`. Apparently the implementation is different from the version in NNlib for negative `x`. Then the NNlib version evaluates `log1pexp` with a positive argument and it's result is added to the negative `x`. Even though we know that the result (without the `log(2)`) is larger than `abs(x)`, i.e., `-x` in this case.

**Comment by cossio** [comment]
That sounds reasonable. 

Though the implementation in Keras also uses softplus: 

![image](https://user-images.githubusercontent.com/10637482/145834794-9db41e4f-59f3-4abd-95dc-f1d3e03a8869.png)
https://github.com/keras-team/keras/blob/2c48a3b38b6b6139be2da501982fd2f61d7d48fe/keras/losses.py#L1613

The only difference is that your version has an extra `abs` call, which I guess has negligible costs.

Numerically I cannot find any differences, both versions evaluate to exactly the same result for all arguments I have tried.

**Comment by devmotion** [comment]
As I said, I can't test it right now - but doesn't the version without `abs` fail for `x = -Inf`?

**Comment by cossio** [comment]
> As I said, I can't test it right now - but doesn't the version without `abs` fail for `x = -Inf`?

Yes it does fail for `x = -Inf`, you are right.

**Comment by devmotion** [comment]
More examples that work better with `abs`:
```julia
julia> mylogcosh(x) = x + log1pexp(- 2 * x) - logtwo

julia> mylogcosh(3.5)
2.8077642858938288

julia> mylogcosh(-3.5) # should be equal to mylogcosh(3.5)
2.8077642858938283

julia> mylogcosh(1e-8)
1.1102230246251565e-16

julia> mylogcosh(-1e-8) # should be equal to mylogcosh(1e-8)
0.0
```
Whereas for the version with `abs`:
```julia
julia> logcosh(3.5)
2.8077642858938288

julia> logcosh(-3.5)
2.8077642858938288

julia> logcosh(-1e-8)
1.1102230246251565e-16

julia> logcosh(1e-8)
1.1102230246251565e-16
```

**Comment by cossio** [comment]
I'm not sure the values for `logcosh(-1e-8)` are correct? I mean, `logcosh(x)` should be around `x^2 / 2` for small `x`, so I expect something closer to `5e-17`.

Compare to the result given by Mathematica

![image](https://user-images.githubusercontent.com/10637482/145980626-ef9c54f1-44aa-4d71-b807-7e6930a8b652.png)

**Comment by devmotion** [comment]
I guess I should have chosen a different example :smile: My main point was not accuracy though but that without `abs` you get different values for `logcosh(x)` and `logcosh(-x)` quite consistently, and for small negative values it even just returns 0.

**Comment by devmotion** [comment]
BTW with `BigFloat` I get  a similar value as Mathematica:
```julia
julia> logcosh(big"1e-8")
4.999999999999999916666666666666668888888888888888821428571428696124396434939272e-17
```

**Comment by devmotion** [comment]
With `Float64` I don't think one can expect a much more accurate result since already `log(2)` is only correct up to around 2.3e-17:
```julia
julia> Float64(logtwo)
0.6931471805599453

julia> big(logtwo)
0.6931471805599453094172321214581765680755001343602552541206800094933936219696955

julia> big(logtwo) - Float64(logtwo)
2.319046813846299615494855463875478650412068000949339362196969553467383712860567e-17
```

**Comment by cossio** [comment]
So there is a large cancellation coming from subtracting log(2).
