### ISSUE TITLE
logsumexp(::SVector) allocates

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/LogExpFunctions.jl#33]
`logsumexp` allocates for static arrays, while for eg `Vector` it doesn't.
```julia
julia> VERSION
v"1.7.2-pre.0"

(@v1.7) pkg> st LogExpFunctions
      Status `~/.julia/environments/v1.7/Project.toml`
  [2ab3a3ac] LogExpFunctions v0.3.6

(@v1.7) pkg> st StaticArrays
      Status `~/.julia/environments/v1.7/Project.toml`
  [90137ffa] StaticArrays v1.3.1

julia> using StaticArrays, LogExpFunctions, BenchmarkTools

julia> x = randn(10)
10-element Vector{Float64}:
 -1.6157998430573786
  1.0318728667047257
  0.26968254689646015
  0.4903347054466403
 -1.117751634134204
 -0.4744921716401031
  0.9685578891398771
 -0.5060390401590071
  0.5209797766678386
 -0.864777496851762

julia> s = SVector(x...);

julia> @btime logsumexp($x)
  93.435 ns (0 allocations: 0 bytes)
2.5045882285138097

julia> @btime logsumexp($s)
  149.875 ns (4 allocations: 256 bytes)
2.5045882285138097
```

**Comment by devmotion** [comment]
We're not explicitly allocating any arrays in the implementation of `logsumexp(::AbstractArray{<:Number})` and I checked that (unsurprisingly) the function is type stable also for `StaticArray`s. My guess right now is that `reduce` (which the implementation is based on: https://github.com/JuliaStats/LogExpFunctions.jl/blob/c8a4c28ffe7b6e4f8d5253e01cef091bb8d2f42c/src/logsumexp.jl#L55) is implemented less efficiently for static arrays and causes these allocations.

**Comment by tpapp** [comment]
I had the same guess but could not pin it down, `reduce(f, ::SVector)` for simple cases is otherwise efficient.

In any case #33 fixes this, let's take further discussion there.

**Comment by tpapp** [comment]
Benchmark for #33: 

```julia
julia> @btime logsumexp($s)
  86.531 ns (0 allocations: 0 bytes)
2.7460914685183573
```

**Comment by tpapp** [comment]
JuliaArrays/StaticArrays.jl#987 will fix this.

**Comment by tpapp** [comment]
Fixed by new release (https://github.com/JuliaRegistries/General/pull/52215).
