### ISSUE TITLE
Support for `Num` from `Symbolics.jl`

### ISSUE THREAD

**Issue by dharasim** [JuliaStats/LogExpFunctions.jl#72]
At the moment, `logsumexp` and related functions do not work with symbolic computations implemented using `Symbolics.jl`:

```julia
using LogExpFunctions
using Symbolics
@variables xs[1:2]
logsumexp(xs)

# ERROR: TypeError: non-boolean (Num) used in boolean context
# Stacktrace:
#  [1] _logsumexp_onepass(X::Symbolics.Arr{Num, 1})
#    @ LogExpFunctions ~/.julia/packages/LogExpFunctions/Vfuhq/src/logsumexp.jl:62
#  [2] _logsumexp
#    @ ~/.julia/packages/LogExpFunctions/Vfuhq/src/logsumexp.jl:52 [inlined]
#  [3] #logsumexp#5
#    @ ~/.julia/packages/LogExpFunctions/Vfuhq/src/logsumexp.jl:30 [inlined]
#  [4] logsumexp(X::Symbolics.Arr{Num, 1})
#    @ LogExpFunctions ~/.julia/packages/LogExpFunctions/Vfuhq/src/logsumexp.jl:30
#  [5] top-level scope
#    @ ~/PlantingSpace/learning/src/tmp_daniel.jl:17
```

A naive implementation of `logsumexp` makes it work as expected:
```julia
LogExpFunctions.logsumexp(xs::AbstractVector{Num}) = log(sum(exp, xs))
logsumexp(xs)
# log(Symbolics._mapreduce(exp, +, xs, Colon(), (:init => false,)))

substitute(logsumexp(xs), Dict(xs => log.([0.5, 0.5]))) == 0
# true
```

It would be great if `Symbolics.Num` could be supported property as an extra dependency.

**Comment by devmotion** [comment]
I don't think there are any specific rules or guidelines yet but to me it would seem more reasonable to instead implement such functionality in Symbolics itself. Since LogExpFunctions is already an indirect dependency of Symbolics.jl this could even be done in the main package and does not require any extension.
