### ISSUE TITLE
xexpy(0, 1000) should be zero

### ISSUE THREAD

**Issue by cossio** [JuliaStats/LogExpFunctions.jl#79]
```julia
julia> xexpy(0, 1000)
NaN
```

I think `xexpy` can handle this better and return zero?

**Comment by devmotion** [comment]
Why should it be 0? At least the current implementation agrees with the docstring.

**Comment by tpapp** [comment]
I also think that we should make `xexpy` finite if `y` is finite and `x` is zero. The purpose of writing a function is precisely to handle these kind of cases.

**Comment by devmotion** [comment]
Fixed by #80.
