### ISSUE TITLE
Add "a" parameter to softplus

### ISSUE THREAD

**Issue by DominiqueMakowski** [JuliaStats/LogExpFunctions.jl#83]
The "a" parameter can control the smooth function, which is useful in the context of regression modelling. 

- See https://link.springer.com/article/10.1007/s00362-023-01509-x

![image](https://github.com/user-attachments/assets/3ca805a3-3119-4f51-a637-f1b2df14984a)

![image](https://github.com/user-attachments/assets/bf138e92-7f0f-4f44-a859-748210b7d143)

Would it be possible to add it as an optional argument (defaulting to 1) ?

**Comment by tpapp** [comment]
Fixed by #85.
